import { motion } from "framer-motion";
import { Sparkles, ShieldCheck, AlertTriangle, Info } from "lucide-react";

interface AIProps {
    recommendation: string;
    analysis: string;
}

export default function GeminiAIInsights({ recommendation, analysis }: AIProps) {
    if (!analysis) return null;

    const isPositive = recommendation === "RESOLVED" || recommendation.includes("Refund");

    return (
        <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mt-8 overflow-hidden rounded-2xl border border-indigo-100 dark:border-indigo-500/30 bg-gradient-to-br from-indigo-50/50 to-white dark:from-indigo-500/5 dark:to-appcard shadow-lg shadow-indigo-500/5"
        >
            <div className="bg-indigo-600 dark:bg-indigo-500 px-5 py-2.5 flex items-center justify-between">
                <div className="flex items-center gap-2 text-white">
                    <Sparkles className="w-4 h-4" />
                    <span className="text-xs font-bold uppercase tracking-widest">Gemini AI Analysis</span>
                </div>
                <div className="flex items-center gap-1.5 px-2 py-0.5 bg-white/20 rounded-full text-[10px] font-bold text-white">
                    <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                    LIVE INSIGHTS
                </div>
            </div>

            <div className="p-6">
                <div className="flex items-start gap-4 mb-6">
                    <div className={`p-3 rounded-xl ${isPositive ? 'bg-green-50 text-green-600 dark:bg-green-500/10 dark:text-green-400' : 'bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-400'}`}>
                        {isPositive ? <ShieldCheck className="w-6 h-6" /> : <AlertTriangle className="w-6 h-6" />}
                    </div>
                    <div>
                        <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">AI Recommendation</p>
                        <h4 className={`text-xl font-bold ${isPositive ? 'text-green-700 dark:text-green-400' : 'text-red-700 dark:text-red-400'}`}>
                            {recommendation || "Pending Analysis..."}
                        </h4>
                    </div>
                </div>

                <div className="relative">
                    <div className="absolute left-0 top-0 bottom-0 w-1 bg-indigo-200 dark:bg-indigo-500/30 rounded-full" />
                    <div className="pl-6">
                        <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 mb-2">
                            <Info className="w-4 h-4" />
                            <span className="text-xs font-bold uppercase tracking-wider">AI Reasoning Log</span>
                        </div>
                        <p className="text-sm text-gray-700 dark:text-gray-300 italic leading-relaxed font-light">
                            "{analysis}"
                        </p>
                    </div>
                </div>

                <div className="mt-6 pt-4 border-t border-indigo-100 dark:border-indigo-500/10">
                    <p className="text-[10px] text-gray-400 italic">
                        Note: This analysis is generated by Gemini AI to assist human decision-making. 
                        The Admin maintains final authority over all resolutions.
                    </p>
                </div>
            </div>
        </motion.div>
    );
}
